spring:
  application:
    name: UserCenter
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scdisk?serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
